### PR TITLE
Create the UI of the Calculator

### PR DESCRIPTION
**Pull request by Ismailco**
- [x] Remove all the boilerplate from CRA.
- [x] Create a directory called components.
- [x] Inside components, create a new Calculator.js file.
- [x] In Calculator.js, create a React component that matches this design from [Project requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_components.md#project-requirements).
- [x] Use class-based components.
- [x] import the calculator.js and use it in your main component.
- [x] Test it in the browser.

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @Ismailco,** 

### **Good job so far!**
You still need to work on some issues to go to the next project, but you are almost there!

## **Highlights**

- Linters are passing 👌.
- PR is very nice 👌.
- The Readme file is good 👌.


## Required Changes ♻️
_Check the comments under the review._

- Nice job mate but you have one small thing passed you, also the `App.js` should be class-based.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ismailco** [comment]
it wasn't clear in the documentation
Ok, Thank you.

**Review by dasileker — APPROVED** [review]
### **Hi @Ismailco,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ismailco** [comment]
Thank's 👍🏼

**Pull request merged**
